backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Created {{collection}} '{{slug}}'"
    update: "Updated {{collection}} '{{slug}}'"

media_folder: "static/images"  # Where images save
public_folder: "/images"       # How they're referenced

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "content/home.yml"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "content", label: "Content", widget: "markdown" }
          - { name: "image", label: "Image", widget: "image" }

  - name: "testimonials"
    label: "Testimonials"
    folder: "content/testimonials/"
    create: true
    fields:
      - { name: "quote", label: "Testimonial", widget: "text" }
      - { name: "author", label: "Author", widget: "string" }
      - { name: "role", label: "Role", widget: "string" }
      - { name: "background", label: "Background Image", widget: "image" }